# 1단계: 빌드
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG NEXT_PUBLIC_KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_ID
ARG NEXTAUTH_SECRET
ARG NEXT_PUBLIC_API_SERVER
ARG NEXT_PUBLIC_DJANGO_SERVER
ARG NEXT_PUBLIC_TRADE_SOCKET_SERVER
ARG NEXT_PUBLIC_USER_ALARM_SOCKET_SERVER
ARG NEXT_PUBLIC_TRADE_SERVER

ENV NEXT_PUBLIC_KAKAO_CLIENT_ID=$NEXT_PUBLIC_KAKAO_CLIENT_ID
ENV KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXT_PUBLIC_API_SERVER=$NEXT_PUBLIC_API_SERVER
ENV NEXT_PUBLIC_DJANGO_SERVER=$NEXT_PUBLIC_DJANGO_SERVER
ENV NEXT_PUBLIC_TRADE_SOCKET_SERVER=$NEXT_PUBLIC_TRADE_SOCKET_SERVER
ENV NEXT_PUBLIC_USER_ALARM_SOCKET_SERVER=$NEXT_PUBLIC_USER_ALARM_SOCKET_SERVER
ENV NEXT_PUBLIC_TRADE_SERVER=$NEXT_PUBLIC_TRADE_SERVER

RUN npm run build

# 2단계: 런타임
FROM node:18-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "start"]